
CREATE TABLE {} (
	[id] [int] NULL,
	[person_id] [int] NULL,
	[household_day_id] [int] NULL,
	[hhno] [int] NULL,
	[pno] [smallint] NULL,
	[day] [smallint] NULL,
	[beghom] [smallint] NULL,
	[endhom] [smallint] NULL,
	[hbtours] [smallint] NULL,
	[wbtours] [smallint] NULL,
	[uwtours] [smallint] NULL,
	[wktours] [smallint] NULL,
	[sctours] [smallint] NULL,
	[estours] [smallint] NULL,
	[pbtours] [smallint] NULL,
	[shtours] [smallint] NULL,
	[mltours] [smallint] NULL,
	[sotours] [smallint] NULL,
	[retours] [smallint] NULL,
	[metours] [smallint] NULL,
	[wkstops] [smallint] NULL,
	[scstops] [smallint] NULL,
	[esstops] [smallint] NULL,
	[pbstops] [smallint] NULL,
	[shstops] [smallint] NULL,
	[mlstops] [smallint] NULL,
	[sostops] [smallint] NULL,
	[restops] [smallint] NULL,
	[mestops] [smallint] NULL,
	[wkathome] [smallint] NULL,
	[pdexpfac] [smallint] NULL
)

